name: CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:16-buster
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    container: node:16-buster
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: contains( github.ref, 'develop') || contains( github.ref, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        run: npx semantic-release
